### ISSUE TITLE
Add pagination to facets

### ISSUE THREAD

**Issue by jimwood** [vivo-community/scholars-react#101]
limit list of returned facet values and add link to show more

NOTE: need to know what happens when "show more" is clicked.  Does it show the next 5 and continue to say "Show more" until they are all shown (for instance)?

Or does it show all the rest and say "Show less"?

Or does is have a pop-up box of options (like TAMU angular site)?

There are other options

**Comment by nymbyl** [comment]
Currently evolving spec - but basic idea seems to be if more than 15 - go to a pop-up that has paging and possibly a search.  Still not resolved how to show those facets selected from pop-up so they can be unchecked.
