### ISSUE TITLE
Search Styling

### ISSUE THREAD

**Issue by jimwood** [vivo-community/scholars-react#107]
Update search styling per attached spec

[Search Design Spec (4.2.20)](https://drive.google.com/file/d/1-6w9v9qX7Thdzqfom5fioTLUTq_8YbNP/view)

[Search Design Spec (3.20.20)](https://drive.google.com/open?id=15PvVKs5Jl-RWf3J1BlIPyngdHGoq-HmB)

**Comment by jimwood** [comment]
ignore 'Text Hierarchy' sizes in top left of spec. Sizes should reflect most recent styling change. Hans to provide updates and comment when complete

**Comment by Hans-Harlacher** [comment]
The search design spec above now links to the updated document.

**Comment by jimwood** [comment]
Changes from 4/7 meeting:
- vertically align filter headers and 'showing' on each search tab
- reduce width of the overview in search results (try %75)
- add underline to 'show more' for facets and add cursor: pointer so they appear more clickable
- final pop-up design in-progress. Current thoughts here: https://drive.google.com/drive/u/0/folders/1qPW-8hcgDVaPzNo3fP4hZljuzWw8JXSO
